import { Raleway } from "next/font/google";
import "./globals.css";
import HeaderSection from "./components/header/HeaderSection";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Graphics app",
  description: "Generated by Graphics app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <HeaderSection />
        {children}
      </body>
    </html>
  );
}
